from enum import Enum


class AuthenticationType(Enum):
    TOKEN = "token"
    OAUTH = "oauth"


class Constants(object):
    CAMPAIGN_GROUP_DATASET = "campaign_group_dataset"
    CAMPAIGN_DATASET = "campaign_dataset"
    CAMPAIGN_ANALYTICS_DATASET = "campaign_analytics_dataset"
    CREATIVE_DATASET = "creative_dataset"
    CREATIVE_ANALYTICS_DATASET = "creatives_analytics_dataset"
    DEFAULT_BATCH_SIZE = 80


class Category(object):
    ACCOUNT = "ACCOUNT"
    GROUP = "GROUP"
    CAMPAIGN = "CAMPAIGN"
    CREATIVE = "CREATIVES"
    CAMPAIGN_ANALYTICS = "CAMPAIGN_ANALYTICS"
    CREATIVE_ANALYTICS = "CREATIVES_ANALYTICS"


COLUMN_NAMES_DICT = {
    Category.ACCOUNT:  ["test", "notifiedOnCreativeRejection", "notifiedOnEndOfCampaign", "servingStatuses", "notifiedOnCampaignOptimization",
                        "type", "version", "reference", "notifiedOnCreativeApproval", "changeAuditStamps", "name", "currency", "id", "status", "exception"],
    Category.GROUP: ["runSchedule", "test", "changeAuditStamps", "name", "servingStatuses", "backfilled", "id", "account", "status", "exception"],
    Category.CAMPAIGN: ["test",
                        "format",
                        "targetingCriteria",
                        "servingStatuses",
                        "locale",
                        "type",
                        "version",
                        "objectiveType",
                        "associatedEntity",
                        "runSchedule",
                        "targeting",
                        "optimizationTargetType",
                        "campaignGroup",
                        "changeAuditStamps",
                        "dailyBudget",
                        "unitCost",
                        "creativeSelection",
                        "costType",
                        "name",
                        "offsiteDeliveryEnabled",
                        "id",
                        "audienceExpansionEnabled",
                        "account",
                        "status",
                        "exception"],
    Category.CREATIVE: ["reference",
                        "variables",
                        "test",
                        "changeAuditStamps",
                        "review",
                        "servingStatuses",
                        "campaign",
                        "id",
                        "type",
                        "version",
                        "status",
                        "exception"],
    Category.CAMPAIGN_ANALYTICS: ["externalWebsitePostClickConversions",
                                  "adUnitClicks",
                                  "companyPageClicks",
                                  "viralOneClickLeads",
                                  "videoFirstQuartileCompletions",
                                  "textUrlClicks",
                                  "viralCommentLikes",
                                  "videoStarts",
                                  "viralExternalWebsiteConversions",
                                  "pivot",
                                  "videoThirdQuartileCompletions",
                                  "cardClicks",
                                  "likes",
                                  "viralComments",
                                  "viralVideoThirdQuartileCompletions",
                                  "oneClickLeads",
                                  "fullScreenPlays",
                                  "viralCardImpressions",
                                  "follows",
                                  "viralOneClickLeadFormOpens",
                                  "conversionValueInLocalCurrency",
                                  "viralFollows",
                                  "otherEngagements",
                                  "viralVideoCompletions",
                                  "cardImpressions",
                                  "leadGenerationMailInterestedClicks",
                                  "opens",
                                  "viralReactions",
                                  "totalEngagements",
                                  "videoViews",
                                  "viralImpressions",
                                  "viralVideoViews",
                                  "dateRange",
                                  "commentLikes",
                                  "costInLocalCurrency",
                                  "viralLikes",
                                  "viralVideoMidpointCompletions",
                                  "viralOtherEngagements",
                                  "shares",
                                  "viralFullScreenPlays",
                                  "videoMidpointCompletions",
                                  "viralCardClicks",
                                  "viralExternalWebsitePostViewConversions",
                                  "viralTotalEngagements",
                                  "viralCompanyPageClicks",
                                  "actionClicks",
                                  "viralShares",
                                  "videoCompletions",
                                  "pivotValue",
                                  "externalWebsitePostViewConversions",
                                  "comments",
                                  "viralVideoStarts",
                                  "costInUsd",
                                  "landingPageClicks",
                                  "oneClickLeadFormOpens",
                                  "impressions",
                                  "sends",
                                  "viralLandingPageClicks",
                                  "viralExternalWebsitePostClickConversions",
                                  "externalWebsiteConversions",
                                  "viralVideoFirstQuartileCompletions",
                                  "leadGenerationMailContactInfoShares",
                                  "clicks",
                                  "reactions",
                                  "viralClicks",
                                  "pivotValues",
                                  "exception"],
    Category.CREATIVE_ANALYTICS: ["externalWebsitePostClickConversions",
                                  "adUnitClicks",
                                  "companyPageClicks",
                                  "viralOneClickLeads",
                                  "videoFirstQuartileCompletions",
                                  "textUrlClicks",
                                  "viralCommentLikes",
                                  "videoStarts",
                                  "viralExternalWebsiteConversions",
                                  "pivot",
                                  "videoThirdQuartileCompletions",
                                  "cardClicks",
                                  "likes",
                                  "viralComments",
                                  "viralVideoThirdQuartileCompletions",
                                  "oneClickLeads",
                                  "fullScreenPlays",
                                  "viralCardImpressions",
                                  "follows",
                                  "viralOneClickLeadFormOpens",
                                  "conversionValueInLocalCurrency",
                                  "viralFollows",
                                  "otherEngagements",
                                  "viralVideoCompletions",
                                  "cardImpressions",
                                  "leadGenerationMailInterestedClicks",
                                  "opens",
                                  "viralReactions",
                                  "totalEngagements",
                                  "videoViews",
                                  "viralImpressions",
                                  "viralVideoViews",
                                  "dateRange",
                                  "commentLikes",
                                  "costInLocalCurrency",
                                  "viralLikes",
                                  "viralVideoMidpointCompletions",
                                  "viralOtherEngagements",
                                  "shares",
                                  "viralFullScreenPlays",
                                  "videoMidpointCompletions",
                                  "viralCardClicks",
                                  "viralExternalWebsitePostViewConversions",
                                  "viralTotalEngagements",
                                  "viralCompanyPageClicks",
                                  "actionClicks",
                                  "viralShares",
                                  "videoCompletions",
                                  "pivotValue",
                                  "externalWebsitePostViewConversions",
                                  "comments",
                                  "viralVideoStarts",
                                  "costInUsd",
                                  "landingPageClicks",
                                  "oneClickLeadFormOpens",
                                  "impressions",
                                  "sends",
                                  "viralLandingPageClicks",
                                  "viralExternalWebsitePostClickConversions",
                                  "externalWebsiteConversions",
                                  "viralVideoFirstQuartileCompletions",
                                  "leadGenerationMailContactInfoShares",
                                  "clicks",
                                  "reactions",
                                  "viralClicks",
                                  "pivotValues",
                                  "exception"]
}
